connector.name=kafka
kafka.nodes=kafka-1:29092,kafka-2:29093,kafka-3:29094
kafka.hide-internal-columns=false
kafka.table-description-supplier=CONFLUENT
kafka.confluent-schema-registry-url=http://schema-registry-1:8081